version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "5000:5000"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "5001:5001"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/user_db  # Ensure the backend knows where to find the MongoDB container

  mongo:
    image: mongo:latest  # Use the official MongoDB image directly
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - ./database/data:/data/db  # Persistent storage for the MongoDB data
      - ./database/init_db.sh:/docker-entrypoint-initdb.d/init_db.sh  # Mount the initialization script
    environment:
      MONGO_INITDB_DATABASE: user_db  # Create 'user_db' on startup
