version: '3.8'

services:
  mongo:
    image: mongo:latest  # Use the official MongoDB image directly
    container_name: mongo-db
    environment:
      MONGO_INITDB_DATABASE: user_db  # This will create the 'user_db' database on startup
    volumes:
      - ./data/db:/data/db  # Store MongoDB data on the host
      - ./init_db.sh:/docker-entrypoint-initdb.d/init_db.sh  # Copy init script for collection setup
    ports:
      - "27017:27017"  # Expose MongoDB port

volumes:
  data-db:
    driver: local
